### ISSUE TITLE
Need a carriage return 

### ISSUE THREAD

**Issue by docktermj** [Senzing/g2explorer#16]
As seen in the screen shot, after the warning about a non-fully functional terminal, when <return> is pressed, a carriage-return / linefeed is not echoed to the the terminal to make the output nicer. 

![Screenshot from 2021-08-27 18-54-21](https://user-images.githubusercontent.com/9219602/131196177-8a4c1652-0371-413d-8b60-4fba54b1f0b2.png)

**Comment by jbutcher21** [comment]
Hi @docktermj, sorry for the delay getting back you on this.  So the problem is I have given control over to the OS to execute the "less" command with auto-scroll to display the table.  I cannot reproduce this error.  Do you have a terminal this always happens on?

**Comment by docktermj** [comment]
@jbutcher21 I'm going to assign this back to me to see if the issue still occurs.  @roncewind has made some changes to the XTerm configuration which may have solved this issue.

**Comment by jbutcher21** [comment]
Can I close this @docktermj ?   I don't thjink its duplicatable.

**Comment by docktermj** [comment]
Yes, I'll close.
