### ISSUE TITLE
When displaying an entity that has relationships, add if the related entities also have further relationships

### ISSUE THREAD

**Issue by antaenc** [Senzing/g2explorer#27]
Consider the relationships on this entity, due to the nature of the match keys I'd expect these to also be inter-related. It would be very helpful to have an indicator for each of the 5 relationships prompting how many relationships each entity has itself. For example, an additional column 'Rels' containing a count of the relationships.

![image](https://user-images.githubusercontent.com/28313221/159808264-5b02c200-dab7-48f8-bfb5-8730857d76de.png)

**Comment by jbutcher21** [comment]
These additional and interrelated relationships are best viewed in the graph.   When you start the G2Explorer, you can use -w WEBAPP_URL to specify where the Senzing web app is listening and a link to the entity's graph will appear in the header section of the get response in the G2Explorer.   Right click this URL to go directly to the graph for the entity.  Note, You can use SenzingGo.py to bring up the webapp.
