### ISSUE TITLE
Typos and errors in help output

### ISSUE THREAD

**Issue by antaenc** [Senzing/g2explorer#77]
Under 'help':

- Current: why - see why two entities or two records did not resolve.
    - Propose: why - see why entities or records did or did not resolve.

Under 'how':

- Current: Each step will either create a virtual entity, add to it or combine it with other virtual entities that were **created gotten** created along the way.
    - Propose: Each step will either create a virtual entity, add to it or combine it with other virtual entities that were created along the way.

- Current: The overview section helps you locate interesting resolution steps **based** that you can search for in the concise or formatted view.
    - Propose: The overview section helps you locate interesting resolution steps that you can search for in the concise or formatted view.

**Comment by jbutcher21** [comment]
Thanks for reviewing this @antaenc.  I made all these changes.
